# Overrrides default config found at https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml

comments:
  active: true
  DeprecatedBlockTag:
    active: true
  OutdatedDocumentation:
    active: true

complexity:
  active: true
  LabeledExpression:
    active: true
  MethodOverloading:
    active: true
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: true

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true

exceptions:
  active: true
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true

naming:
  active: true
  FunctionMaxLength:
    active: true
  FunctionMinLength:
    active: true
  LambdaParameterNaming:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  VariableMaxLength:
    active: true

performance:
  active: true
  CouldBeSequence:
    active: true
    threshold: 3

potential-bugs:
  active: true
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  ExitOutsideMain:
    active: true
  ImplicitUnitReturnType:
    active: true
  LateinitUsage:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingPackageDeclaration:
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true

style:
  active: true
  CanBeNonNullable:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassShouldBeImmutable:
    active: false # Just documenting that I would normally enable this in the average codebase, but DS&A-focused problems often benefit from mutability
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExpressionBodySyntax:
    active: true
    includeLineWrapping: true
  ForbiddenImport:
    active: true
  ForbiddenMethodCall:
    active: true
  ForbiddenSuppress:
    active: true
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '10'
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: true
  OptionalUnit:
    active: true
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantExplicitType:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    active: false # Would normally enable, but algorithmic problems often benefit from many returns.
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryInnerClass:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseDataClass:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
